blueprints/front.py
from flask import Blueprint,render_template,request,current_app
from models.post import BoardModel,PostModel,CommentModel
from flask_paginate import Pagination

bp = Blueprint("front",__name__,url_prefix="")

@bp.route('/')
def index():
    posts = PostModel.query.all()
    boards = BoardModel.query.all()

    # 通过查询传参得到，当前页数，在url中
    page = request.args.get("page",type=int,default=1)

    board_id = request.args.get("board_id",type=int,default=0)

    start = (page - 1) * current_app.config.get("PER_PAGE_COUNT")
    end = start + current_app.config.get("PER_PAGE_COUNT")

    query_posts = PostModel.query.order_by(PostModel.create_time.desc())

    if board_id:
        query_posts = query_posts.filter_by(board_id=board_id)

    total = query_posts.count()

    posts = query_posts.slice(start,end)

    pagination = Pagination(bs_version=5,page=page,total=total,outer_window=0,inner_window=2,
                            alignment="center")
    
    context = {
        "posts": posts,
        "boards": boards,
        "pagination": pagination,
        "current_board": board_id
    }
    current_app.logger.info("index页面被请求了")
    return render_template("index.html", **context)

blueprints/post.py
from flask import Blueprint,render_template,request,g,flash,redirect,url_for
from models.post import BoardModel,PostModel,CommentModel
from util.decorators import login_required
from forms.post import PublicPostForm,CommentForm
from exts import db
from util import restful

bp = Blueprint("post",__name__,url_prefix="/post")

@bp.route('/public',methods=['GET','POST'])
# 添加装饰器，需要先登录才能发布帖子
@login_required
def public():
    form = PublicPostForm()
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template("front/public_post.html",boards=boards,form=form)
    else: 
        data = request.get_json()
        form = PublicPostForm(data=data)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data

            print(title,content,board_id)

            post = PostModel(title=title,content=content,board_id=board_id,author=g.user)
            db.session.add(post)
            db.session.commit()
            return restful.ok()
        else:
            message = form.messages[0]
            return restful.params_error(message=message)

@bp.route('/detail/<int:post_id>')
def post_detail(post_id):
    form=CommentForm()
    post = PostModel.query.get(post_id)
    post.read_count += 1
    db.session.commit()

    return render_template("front/post_detail.html",post=post,form=form)

@bp.route('/<int:post_id>/comment',methods=['POST'])
@login_required
def post_comment(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        # 获取前端属性为“content”标签中的内容
        content = form.content.data
        comment = CommentModel(content=content,post_id=post_id,author=g.user)
        db.session.add(comment)
        db.session.commit()
    else:
        for message in form.messages:
            flash(message)
    return redirect(url_for('post.post_detail',post_id=post_id))

blueprints/user.py
from flask import Blueprint,current_app,render_template,request,redirect,url_for,flash,g,session
from flask_mail import Message
from exts import mail,cache,db
import random
import string
from forms.register import RegisterForm
from forms.login import LoginForm
from forms.user import EditProfileForm
from models.user import UserModel
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
from util.decorators import login_required
import os



"""
文件名: user
功能: 创建蓝图路由，访问路由，执行对应的视图函数
作者: cube
创建时间: 2025-07-12
"""

# 点击"发送验证码"，执行的视图函数
bp = Blueprint("user",__name__,url_prefix="/user")
@bp.route('/mail/captcha/<email>')
def mail_captcha(email):
    verification_code = ''.join(random.choices(string.digits,k=6))
    subject = '验证码'
    body = f'【query】请接收验证码:{verification_code}。如非本人操作，请忽略此信息'
    # message = Message(subject=subject,recipients=[email],body=body)
    # mail.send(message)  
    # 改用celery的方式
    current_app.celery.send_task("send_mail",(email,subject,body))
    cache.set(email,verification_code,timeout=100)
    return {"status":"success"}

@bp.route("/signup",methods=['GET','POST'])
def signup():
    form = RegisterForm()
    if request.method == 'GET':
        return render_template("signup.html",form=form)
    else:
        # html中的name字段需要和form.   验证类中的相同
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.signin"),form=form)
        else:
            for message in form.messages:
                flash(message)
            return render_template("signup.html", form=form)
        
@bp.route("/login",methods=['GET','POST'])
def login():
    form = LoginForm()
    if request.method == 'GET':
        return render_template("login.html",form=form)
    else:
        if form.validate():
            return redirect(url_for("front.index"))
        else:
            for message in form.messages:
                flash(message)
            return render_template("login.html",form=form)
        
@bp.route('/profile/<string:user_id>')
def profile(user_id):
    form = EditProfileForm()
    user = UserModel.query.get(user_id)
    print(g.user.avatar)
    is_mine = False
    if hasattr(g,"user") and g.user.id == user_id:
        is_mine = True

    context = {
        "user": user,
        "is_mine": is_mine,
        "form": form
    }
    
    return render_template("front/profile.html",**context)

# FIXME：点击退出，返回无属性“user”
@bp.route('/logout')
def logout():
    session.clear()
    return redirect("/")

@bp.route('/profile/edit',methods=['GET','POST'])
@login_required
def edit_profile():
    # 实例化表单类，传入提交表单的数据
    # request 是 Flask 提供的一个全局对象，代表当前的 HTTP 请求
    # request.form只包含文本字段，request.files只包含文件字段
    # 
    form = EditProfileForm(CombinedMultiDict([request.form,request.files]))
    if form.validate_on_submit():
        username = form.username.data
        avatar = form.avatar.data
        signature =  form.signature.data
        
        #如果上传了头像
        if avatar:
            # 生成安全的文件名
            filename = secure_filename(avatar.filename)
            # 拼接头像存储路径
            avatar_path = os.path.join(current_app.config.get("AVATARS_SAVE_PATH"),filename)
            # 保存文件到指定地址
            avatar.save(avatar_path)
            #设置头像的URL
            #g.user.avatar = url_for("media.media_file",filename=os.path.join("avatars",filename))
            g.user.avatar = url_for('static', filename=f'avatars/{filename}')
        g.user.username = username
        g.user.signature = signature
        db.session.commit()
        return redirect(url_for("user.profile",user_id=g.user.id))
    else:
        for message in form.messages:
            flash(message)
        return redirect(url_for("user.profile",user_id=g.user.id))

templates/front/post_detail.html
{% extends "base.html" %} {% block title%}{{ post.title }}{% endblock %} {%
block head %}
<link
  rel="stylesheet"
  href="https://cdn.staticfile.net/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css"
/>
{% endblock %} {% block body%}

<section class="container-lg">
  <h2 class="text-center">{{ post.title }}</h2>
  <p class="post-info-group">
    <span>发表时间:{{ post.create_time }}</span>
    <span>作者: <a href="{{ url_for('user.profile',user_id=post.author.id)}}">{{ post.author.username }}</a></span>
    <span>所属板块: {{ post.board.name }}</span>
    <br>
    <span>阅读量:{{ post.read_count }}</span>
    <span>评论数量:{{ post.comments|length }}</span>
  </p>
  <article class="post-content" id="post-content">
    {{ post.content|safe}}
  </article>

  <form
    method="POST"
    action="{{ url_for('post.post_comment',post_id=post.id)}}"
    autocomplete="off"
  >
    {{ form.hidden_tag() }}
    <!-- 应该包含 csrf_token 字段 -->
    <div class="my-3">
      <textarea
        type="text"
        class="form-control"
        placeholder="写点什么..."
        name="content"
        rows="1"
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">
      <i class="bi bi-send"> 发布</i>
    </button>
  </form>

  <div id="comments" class="my-2">
      {% for comment in post.comments %}
      <div class="mb-4 border-bottom border-1 pb-2">
        <div class="card-body">
          <h5 class="card-title">{{ comment.author.username }}</h5>
          <small class="card-subtitle mb-2 text-muted">{{ comment.create_time}}</small>
          <p class="card-text">{{ comment.content }}</p>
        </div>
      </div>
      {% endfor %}
  </div>
</section>

<script>
  const textarea = document.querySelector('textarea[name="content"]');

  textarea.addEventListener("input", function () {
    this.style.height = "auto"; // 先重置高度
    this.style.height = this.scrollHeight + "px"; // 设置为内容高度
  });
</script>

{% endblock %}

templates/front/profile.html
{% extends "base.html" %}
{% block title%}个人中心{% endblock %}
{% block head %}{% endblock %}
{% block body%}

<section class="container">
    <div>
        {# 先判断 user 是否存在，不存在则显示提示 #}
        {% if not user %}
            <div class="alert alert-danger">用户不存在或已被删除</div>
        {% else %}
            <form action="{{ url_for('user.edit_profile') }}" method="post" enctype="multipart/form-data">
                {# 注意：表单需要添加 method="post" 才能提交数据 #}
                {{ form.hidden_tag() }}
                <table class="table table-bordered mt-5">
                    <tbody>
                        <tr>
                            <th width="100px">用户名：</th>
                            <td>
                                {% if is_mine %}
                                    <input type="text" name="username" value="{{ user.username }}">
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>头像：</th>
                            <td>
                                {# 即使 user 存在，也需判断 email 是否有效 #}
                                {% if user.avatar %}
                                    <img src="{{ user.avatar }}" width="200" alt="" >
                                {% else %}
                                    {# 邮箱为空时显示默认头像 #}
                                    <img class="avatar" src="{{ avatars.gravatar(user.email|email_hash)|replace('https://gravatar.com/avatar/', 'https://gravatar.loli.net/avatar/') }}" width="200" alt="用户头像">

                                {% endif %}

                                {% if is_mine %}
                                    <!-- .jpg 和 .jpeg 都是 JPEG 图像格式 -->
                                    <input type="file" name="avatar" accept="image/jpeg image/png">
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>签名：</th>
                            <td>
                                {% if is_mine %}
                                    <input type="text" name="signature" value="{{ user.signature or ''}}">
                                {% else %}
                                    {{ user.signature or '暂无签名' }}
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                {% if is_mine %}
                    <div style="text-align: center;">
                        <button class="btn btn-primary">保存</button>
                    </div>
                {% endif %}
            </form>
        {% endif %}
    </div>
</section>

{% endblock %}

templates/front/public_post.html
{% extends "base.html" %} {% block title%}发布帖子{% endblock %} {% block head
%}
<link
  href="https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css"
  rel="stylesheet"
/>
<style>
  #toolbar-container {
    border-bottom: 1px solid #ccc;
  }
  #editor-container {
    height: 400px;
  }
</style>
{% endblock %}{% block body%}
<div class="container my-3">
  <h3 class="text-center">发布帖子</h3>
  <div class="row justify-content-center">
    <div class="col-lg-8 my-3">
      <!-- 点击类型为“type=submit”的按钮，将表单数据提交给对应的url -->
      <form
        method="POST"
        autocomplete="off"
      >
      {{ form.hidden_tag() }}
        <input
          type="text"
          id="title"
          name="title"
          placeholder="标题"
          class="form-control"
          required=""
        />
        <select name="board_id" class="form-select my-2" id="board_id">
          {% for board in boards %}
          <option value={{ board.id }}>{{ board.name }}</option>
          {% endfor %}
        </select>

        <div id="editor-wrapper" class="border rounded">
          <div id="toolbar-container"><!-- 工具栏 --></div>
          <div id="editor-container"><!-- 编辑器 --></div>
        </div>

        <div class="my-3 text-center">
          <button class="btn btn-primary w-100" type="button" id="submit">发布</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div
      class="col-md-6 col-lg-4 position-fixed bottom-0 end-0 p-3"
      style="z-index: 11"
    >
      {%with messages = get_flashed_messages() %} {%if messages %}
      <div class="form-group">
        <ul>
          {% for message in messages %}
          <li class="text-danger">{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %} {% endwith %}
    </div>
  </div>
</div>

<script src="https://unpkg.com/@wangeditor/editor@latest/dist/index.js"></script>
<script>


  // 渲染富文本编辑器
  const { createEditor, createToolbar } = window.wangEditor;
  const editor = createEditor({
    selector: '#editor-container',
    html: '<p><br></p>',
    placeholder: '请输入内容...',
    mode: 'simple'
  });
  const toolbar = createToolbar({
    editor: editor,
    selector: '#toolbar-container',
    mode: 'simple'
  });

  // 2. 提交事件处理
  const submit_btn = document.querySelector('#submit');
  submit_btn.addEventListener('click', async (event) => {
    // 获取表单数据
    const data = {
      title: document.querySelector('#title').value,
      board_id: document.querySelector('#board_id').value,
      content: editor.getHtml()
    }
    // response是响应报文
    try {
      const response = await fetch('/post/public',{
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': document.querySelector('input[name="csrf_token"]').value  // 处理CSRF保护
        },
        body: JSON.stringify(data)  // 转为JSON格式发送
      }); 
    // 获取响应体中的内容
    // 后端返回 状态行，响应头，响应体
    const result = await response.json();
      if (response.ok) {
        alert('发布成功！');
        window.location.href = '/';  // 跳转到首页
      } else {
        alert('发布失败：' + result.message);
      }
    } catch (error) {
      console.error('提交失败：', error);
      alert('网络错误，请重试');
    }
  });
</script>
{% endblock %}