forms/cms.py
from wtforms import StringField,ValidationError,IntegerField,BooleanField
from wtforms.validators import Email,EqualTo,Length,InputRequired
from exts import cache
from models.user import UserModel
from .baseform import BaseForm

class AddStaffForm(BaseForm):
        email = StringField(validators=[Email(message="请输入正确的邮箱格式!")])
        role = IntegerField(validators=[InputRequired(message="请选择角色")])

class EditStaffForm(BaseForm):
        is_staff = BooleanField(validators=[InputRequired(message="请选择是否为员工")])
        role = IntegerField(validators=[InputRequired(message="请选择角色")])

blueprints/cms.py
from flask import Blueprint,render_template,redirect,g,jsonify,request,flash,url_for
from util.hooks import before_request
from models.user import PermissionEnum,UserModel,RoleModel
from util.decorators import permission_required
from forms.cms import AddStaffForm,EditStaffForm
from exts import db


bp = Blueprint("cms",__name__,url_prefix="/cms")

@bp.before_request
def cms_before_request():
    if not hasattr(g,"user") or g.user.is_staff == False:
        return redirect("/")
    
@bp.context_processor
def cms_context_processor():
    return {"PermissionEnum": PermissionEnum}


@bp.route('/index')
def cms_index():
    users = UserModel.query.filter_by(is_staff=True).all()
    return render_template("/cms/staff_list.html",users=users)


@bp.route('/staff/list')
def staff_list():
    users = UserModel.query.filter_by(is_staff=True).all()
    return render_template("/cms/staff_list.html",users=users)

@bp.route('/staff/add',methods=['GET','POST'])
@permission_required(PermissionEnum.CMS_USER)
def staff_add():
    form = AddStaffForm()
    if request.method == 'GET':
        roles = RoleModel.query.all()
        return render_template("cms/staff_add.html",roles=roles,form=form)
    else:
        if form.validate_on_submit():
            email = form.email.data
            role_id = form.role.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                flash('没有此用户')
                return redirect(url_for("cms.staff_list"))
            user.is_staff = True
            user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.staff_list"))
        
@bp.route('/staff/edit/<string:user_id>',methods=['GET','POST'])
def staff_edit(user_id):
    target_user = UserModel.query.get(user_id)
    form = EditStaffForm()
    if request.method == 'GET':
        roles = RoleModel.query.all()
        
        return render_template("cms/staff_edit.html",target_user=target_user,roles=roles,form=form)
    else:
        if form.validate_on_submit():
            is_staff = form.is_staff.data
            role_id = form.role.data
            target_user.is_staff = is_staff
            if target_user.role.id != role_id:
                target_user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.staff_edit",user_id=user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("cms.staff_edit",user_id=user_id))
    
    

blueprints/post.py
from flask import Blueprint,render_template,request,g,flash,redirect,url_for
from models.post import BoardModel,PostModel,CommentModel
from util.decorators import login_required
from forms.post import PublicPostForm,CommentForm
from exts import db
from util import restful

bp = Blueprint("post",__name__,url_prefix="/post")

@bp.route('/public',methods=['GET','POST'])
# 添加装饰器，需要先登录才能发布帖子
@login_required
def public():
    form = PublicPostForm()
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template("front/public_post.html",boards=boards,form=form)
    else: 
        data = request.get_json()
        form = PublicPostForm(data=data)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data

            print(title,content,board_id)

            post = PostModel(title=title,content=content,board_id=board_id,author=g.user)
            db.session.add(post)
            db.session.commit()
            return restful.ok()
        else:
            message = form.messages[0]
            return restful.params_error(message=message)

@bp.route('/detail/<int:post_id>')
def post_detail(post_id):
    form=CommentForm()
    post = PostModel.query.get(post_id)
    post.read_count += 1
    db.session.commit()

    return render_template("front/post_detail.html",post=post,form=form)

@bp.route('/<int:post_id>/comment',methods=['POST'])
@login_required
def post_comment(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        # 获取前端属性为“content”标签中的内容
        content = form.content.data
        comment = CommentModel(content=content,post_id=post_id,author=g.user)
        db.session.add(comment)
        db.session.commit()
    else:
        for message in form.messages:
            flash(message)
    return redirect(url_for('post.post_detail',post_id=post_id))

blueprints/user.py
from flask import Blueprint,current_app,render_template,request,redirect,url_for,flash,g,session
from flask_mail import Message
from exts import mail,cache,db
import random
import string
from forms.register import RegisterForm
from forms.login import LoginForm
from forms.user import EditProfileForm
from models.user import UserModel
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
from util.decorators import login_required
import os



"""
文件名: user
功能: 创建蓝图路由，访问路由，执行对应的视图函数
作者: cube
创建时间: 2025-07-12
"""

# 点击"发送验证码"，执行的视图函数
bp = Blueprint("user",__name__,url_prefix="/user")
@bp.route('/mail/captcha/<email>')
def mail_captcha(email):
    verification_code = ''.join(random.choices(string.digits,k=6))
    subject = '验证码'
    body = f'【query】请接收验证码:{verification_code}。如非本人操作，请忽略此信息'
    # message = Message(subject=subject,recipients=[email],body=body)
    # mail.send(message)  
    # 改用celery的方式
    current_app.celery.send_task("send_mail",(email,subject,body))
    cache.set(email,verification_code,timeout=100)
    return {"status":"success"}

@bp.route("/signup",methods=['GET','POST'])
def signup():
    form = RegisterForm()
    if request.method == 'GET':
        return render_template("signup.html",form=form)
    else:
        # html中的name字段需要和form.   验证类中的相同
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email,username=username,password=password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.signin"),form=form)
        else:
            for message in form.messages:
                flash(message)
            return render_template("signup.html", form=form)
        
@bp.route("/login",methods=['GET','POST'])
def login():
    form = LoginForm()
    if request.method == 'GET':
        return render_template("login.html",form=form)
    else:
        if form.validate():
            return redirect(url_for("front.index"))
        else:
            for message in form.messages:
                flash(message)
            return render_template("login.html",form=form)
        
@bp.route('/profile/<string:user_id>')
def profile(user_id):
    form = EditProfileForm()
    user = UserModel.query.get(user_id)
    print(g.user.avatar)
    is_mine = False
    if hasattr(g,"user") and g.user.id == user_id:
        is_mine = True

    context = {
        "user": user,
        "is_mine": is_mine,
        "form": form
    }
    
    return render_template("front/profile.html",**context)

# FIXME：点击退出，返回无属性“user”
@bp.route('/logout')
def logout():
    session.clear()
    return redirect("/")

@bp.route('/profile/edit',methods=['GET','POST'])
@login_required
def edit_profile():
    # 实例化表单类，传入提交表单的数据
    # request 是 Flask 提供的一个全局对象，代表当前的 HTTP 请求
    # request.form只包含文本字段，request.files只包含文件字段
    # 
    form = EditProfileForm(CombinedMultiDict([request.form,request.files]))
    if form.validate_on_submit():
        username = form.username.data
        avatar = form.avatar.data
        signature =  form.signature.data
        
        #如果上传了头像
        if avatar:
            # 生成安全的文件名
            filename = secure_filename(avatar.filename)
            # 拼接头像存储路径
            avatar_path = os.path.join(current_app.config.get("AVATARS_SAVE_PATH"),filename)
            # 保存文件到指定地址
            avatar.save(avatar_path)
            #设置头像的URL
            #g.user.avatar = url_for("media.media_file",filename=os.path.join("avatars",filename))
            g.user.avatar = url_for('static', filename=f'avatars/{filename}')
        g.user.username = username
        g.user.signature = signature
        db.session.commit()
        return redirect(url_for("user.profile",user_id=g.user.id))
    else:
        for message in form.messages:
            flash(message)
        return redirect(url_for("user.profile",user_id=g.user.id))

templates/cms/sidebar-mode.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>管理系统</title>
    <link
      href="https://cdn.bootcdn.net/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link href="/static/base.css" rel="stylesheet" />
    <style>
      .sidebar {
        width: 220px;
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        background-color: #f8f9fa;
        padding-top: 1rem;
        border-right: 1px solid #dee2e6;
      }
      .content {
        margin-left: 220px;
        padding: 2rem;
      }
      .nav-link {
        color: black;
      }
    </style>
    {% block head %}{% endblock %}
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg fixed-top"
      style="background-color: rgb(250, 232, 244)"
    >
      <div class="container">
        <a href="#" class="navbar-brand">Query</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav">
            <li class="nav-item"><a href="/" class="nav-link">首页</a></li>
            <li class="nav-item">
              <a href="{{ url_for('post.public') }}" class="nav-link">发布</a>
            </li>
            <li class="nav-item"><a href="#" class="nav-link">chat AI</a></li>
            <li class="nav-item"><a href="#" class="nav-link">好友</a></li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form>
          <ul class="navbar-nav ms-auto">
            {% if g.user %}
            <!-- g.user.is_staff需要内嵌，不然会说g.user没is_staff属性 -->
            {% if g.user.is_staff %}
            <li class="nav-item">
              <a href="{{ url_for('cms.cms_index') }}" class="nav-link"
                >管理系统</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                href="{{ url_for('user.profile',user_id=g.user.id) }}"
                class="nav-link"
                >{{ g.user.username}}</a
              >
            </li>
            <li class="nav-item">
              <a href="{{ url_for('user.logout') }}" class="nav-link"
                >退出登录</a
              >
            </li>
            {% else %}
            <!-- 这里的href是视图函数端点，而不是url -->
            <li class="nav-item">
              <a href="{{ url_for('user.login') }}" class="nav-link">登录</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('user.signup') }}" class="nav-link">注册</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div id="body">
        <div class="sidebar">
  <h5 class="text-center mb-4">管理菜单</h5>
  <ul class="nav flex-column">
    <li class="nav-item">
      <a
        class="nav-link {% if request.endpoint == 'cms.cms_index' %}active{% endif %}"
        href="{{ url_for('cms.cms_index') }}"
      >
        首页
      </a>
    </li>

    {% set user = g.user %} {% if user.role.has_permission(PermissionEnum.POST)
    %}
    <li class="nav-item">
      <a class="nav-link" id="post-manage" href="{{ url_for('cms.staff_list') }}">帖子管理</a>
    </li>
    {% endif %} {% if user.has_permission(PermissionEnum.COMMENT) %}
    <li class="nav-item">
      <a class="nav-link" href="#">评论管理</a>
    </li>
    {% endif %} {% if user.has_permission(PermissionEnum.BOARD) %}
    <li class="nav-item">
      <a class="nav-link" id="" href="#">板块管理</a>
    </li>
    {% endif %} {% if user.has_permission(PermissionEnum.FRONT_USER) %}
    <li class="nav-item">
      <a class="nav-link" href="#">前台用户管理</a>
    </li>
    {% endif %} {% if user.has_permission(PermissionEnum.CMS_USER) %}
    <li class="nav-item">
      <a class="nav-link" id="staff-manage" href="{{ url_for('cms.staff_list') }}">员工管理</a>
    </li>
    {% endif %}
  </ul>
</div>

<!-- 主体内容区域 -->
<div id="page-content" class="content">
  <!-- 这里可以放每个页面不同的内容 -->
  {% block body %}{%  endblock %}
</div>
    </div>

    <script src="https://cdn.bootcdn.net/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/cms/staff_add.html
{% extends "cms/sidebar-mode.html" %} {% block body%}
<section>
    <h3>添加员工</h3>
    <form method="POST" action="{{ url_for('cms.staff_add') }}" autocomplete="off" class="w-25">
        {{ form.hidden_tag() }}
        <div class="my-3">
            <input class="form-control" type="email" name="email" placeholder="邮箱地址"></input>
        </div>
        <label class="form-label">角色：</label>
        {% for role in roles %}
            <div class="form-check form-check-inline mb-3">
                <input type="radio" class="form-check-input" name="role" id="{{ role.id }}" value="{{ role.id }}">
                <label class="form-check-label" for="{{ role.id }}">{{ role.name }}</label>
            </div>
        {% endfor %}
        <div class="mb-3 text-center">
            <input type="submit" class="btn btn-primary w-50" value="提交"></input>
        </div>
    </form>
</section>

{% endblock %}

templates/cms/staff_edit.html
{% extends "cms/sidebar-mode.html" %} {% block body%}
<section>
    <h3>编辑员工</h3>
    <form method="POST" action="{{ url_for('cms.staff_edit',user_id=target_user.id) }}" autocomplete="off" class="w-25">
        {{ form.hidden_tag() }}
        <div class="d-flex align-items-center my-3">
            <label class="form-label me-2 mb-0">邮箱：</label>
            <span class="form-control" style="width: auto;">{{ target_user.email }}</span>
        </div>
        <div class="my-3">
            <label class="form-label">员工：</label>
            <input type="radio" class="form-check-input" name="is_staff" id="staff-yes" value="true" {% if target_user.is_staff %}checked{% endif %}>
            <label class="form-check-label" for="staff-yes">是</label>
            <input type="radio" class="form-check-input" name="is_staff" id="staff-no" value="false" {% if not target_user.is_staff %}checked{% endif %}>
            <label class="form-check-label" for="staff-no">否</label>
        </div>
        <label class="form-label">角色：</label>
        {% for role in roles %}
            <div class="form-check form-check-inline mb-3">
                <input type="radio" class="form-check-input" name="role" id="{{ role.id }}" value="{{ role.id }}" {% if target_user.role_id == role.id %}checked{% endif %}>
                <label class="form-check-label" for="{{ role.id }}">{{ role.name }}</label>
            </div>
        {% endfor %}
        <div class="mb-3 text-center">
            <input type="submit" class="btn btn-primary w-50" value="确认修改">
        </div>
    </form>
</section>

{% endblock %}

templates/cms/staff_list.html
{% extends "cms/sidebar-mode.html" %} {% block body%}

<section>
  <h3>员工管理</h3>
  <a href="{{ url_for('cms.staff_add') }}" class="btn btn-primary mb-2">添加员工</a>
  <table class="table table-striped table-hover table-bordered align-middle text-center">
    <thead class="table-primary">
      <tr>
        <th>序号</th>
        <th>邮箱</th>
        <th>用户名</th>
        <th>加入时间</th>
        <th>角色</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ loop.index}}</td>
            <td>{{ user.email}}</td>
            <td>{{ user.username}}</td>
            <td>{{ user.join_time}}</td>
            <td>{{ user.role.name}}</td>
            <td>{% if not user.has_permission(PermissionEnum.CMS_USER) %}
                    <a href="{{ url_for('cms.staff_edit',user_id=user.id) }}" class="btn btn-primary btn-sm">编辑</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</section>

{% endblock %}